### ISSUE TITLE
Upgrade glob to latest

### ISSUE THREAD

**Issue by YouriT** [substack/bulk-require#10]
Hi,

`glob` used to use `minimatch@0.3.0` which has a Regex DoS issue. Could you upgrade this package please?

Thank you!

**Comment by YouriT** [comment]
Didn't see there was a PR #4 about it... Could you validate it please.

**Comment by kahwee** [comment]
#4 is superseded by #11.

**Comment by YouriT** [comment]
ping @substack

**Comment by BrandonCopley** [comment]
Any chance we could get this done, there are DOS vulnerability issues related to this as long as the package isn't updated.

**Comment by BrandonCopley** [comment]
When will this update be made?

**Comment by yamboy1** [comment]
I've tried asking the owner, hopefully that works

**Comment by erikvold** [comment]
https://snyk.io/test/npm/bulk-require

**Comment by yamboy1** [comment]
@leetreveil @gmaclennan @jdiamond @substack 

Could someone please merge #11? This is a big issue and I can't believe any of you haven't done anything about this! It's been almost a whole year!

**Comment by gmaclennan** [comment]
fixed and released in v1.0.1
