### ISSUE TITLE
Make "globs" parameter optional?

### ISSUE THREAD

**Issue by lukehorvat** [substack/bulk-require#3]
The second parameter is one or more globs. It seems intuitive to me that omitting the globs entirely would require every file in the base directory (i.e. the equivalent of specifying a `**/*` glob), but currently this is not the case.

Example:

``` javascript
var bulk = require('bulk-require');

bulk(__dirname + '/data', []); // Globs known but do not match anything. No modules required.
bulk(__dirname + '/data', ''); // Globs known but do not match anything. No modules required.
bulk(__dirname + '/data', '**/*'); // Globs known. All modules required.
bulk(__dirname + '/data'); // Globs unknown. All modules required.
```

**Comment by gmaclennan** [comment]
Closing this, since doesn't seem to have much activity...
