### ISSUE TITLE
convert hypenated files to camelCase

### ISSUE THREAD

**Issue by colthreepv** [substack/bulk-require#5]
I think such a library could use the implicit conversion from hypenated (`simple-string`) to camelCase (`simpleString`), so that it can be called like this:

`modules/simple-string.js`:

``` javascript
module.exports = 'Hello World';
```

`main.js`:

``` javascript
var bulk = require('bulk-require');
var modules = bulk(__dirname, ['modules/*.js]);
console.log(modules.simpleString);
// instead of
console.log(modules['simple-string']);
```

**Comment by gmaclennan** [comment]
I think this would make most sense to remain outside this module, since it is a user-preference and could create confusion about module names.

This can be easily done with a small amount of code:

```js
const camelCase = require('camelcase')
modules = Object.keys(modules).reduce(function (acc, name) {
  acc[camelCase(name)] = modules[name]
  return acc
}, {})
```
